# Ejercicios Modulos (41-50)

## Ejercicio 41
¿A qué número hay que elevar 2 para que resulte 20? ¿A qué número hay que elevar 2 para que resulte 46? ¿A qué número hay que elevar 2 para que resulte 180? Realiza las acciones debidas para poder resumir todas las respuestas anteriores en un único array

In [1]:
import numpy as np

numeros = np.array([20, 46, 180])
resultado = np.log2(numeros)

print(resultado)    

[4.32192809 5.52356196 7.4918531 ]


## Ejercicio 42
¿A qué número hay que elevar 10 para que resulte 150? ¿ A qué número hay que elevar 10 para que resulte 1000? ¿A qué número hay que elevar 10 para que resulte 777? Realiza las acciones debidas para poder resumir todas las respuestas anteriores en un único array.

In [2]:
import numpy as np

numeros = np.array([150, 1000, 777])
resultado = np.log10(numeros)

print(resultado)

[2.17609126 3.         2.89042102]


## Ejercicio 43
¿Cuál es el mínimo común múltiplo de los números 18,12 y 42? Calcula el resultado a partir de un array constituido por dichos números y empleando las funciones de NumPy adecuadas.

In [3]:
import numpy as np

numeros = np.array([18, 12, 42])
resultado = np.gcd.reduce(numeros)

print(resultado)

6


## Ejercicio 44
¿Cuál es el máximo común divisor de los números 20, 24 y 32? Calcula el resultado a partir de un array constituido por dichos números y empleando las funciones de NumPy adecuadas.

In [4]:
import numpy as np

numeros = np.array([20, 24, 32])
resultado = np.lcm.reduce(numeros)

print(resultado)

480


## Ejercicio 45
1. Crea un array que contenga las edades de 20 personas aleatorias (fruto de una encuesta).

In [5]:
import numpy as np

edades = np.random.randint(18, 80, 20)
print(edades)

[67 36 44 63 65 51 65 75 69 20 50 25 34 74 37 28 26 71 52 32]


2. A partir del array anterior, crea un conjunto de valores únicos con las edades de esas 20 personas (puesto que es bastante probable que la edad se repita entre los encuestados). Finalmente, visualiza el conjunto por pantalla.

In [6]:
conjunto = np.unique(edades)

print(conjunto)

[20 25 26 28 32 34 36 37 44 50 51 52 63 65 67 69 71 74 75]


## Ejercicio 46
1. Crea un array que contenga el color favorito de 20 personas (fruto de otra encuesta). Al preguntar a otras 20 personas más, se ha obtenido otro array de 20 elementos.

In [7]:
import numpy as np

colores = np.array(["rojo", "azul", "verde", "rosa", "naranja", "rojo", "naranja", "verde", "azul", "azul", "negro", "negro", "morado", "rojo", "rosa", "rojo", "azul", "verde", "blanco", "marron"])
colores2 = np.array(["marron", "celeste", "verde", "blanco", "blanco", "rojo", "verde", "verde", "amarillo", "negro", "morado", "azul", "verde", "amarillo", "rojo", "rojo", "azul", "verde", "amarillo", "magenta"])

2. Elabora, a partir de los dos arrays anteriores, un conjunto único con los colores favoritos en la totalidad de la encuesta (ya que es muy probable que algunas respuestas se repitan en el muestreo).

In [9]:
conjunto = np.concatenate((colores, colores2))
conjunto2 = np.unique(conjunto)

print(conjunto2)

['amarillo' 'azul' 'blanco' 'celeste' 'magenta' 'marron' 'morado'
 'naranja' 'negro' 'rojo' 'rosa' 'verde']


## Ejercicio 47
1. Crea un array que contenga el grupo sanguíneo de 20 personas (fruto de otra encuesta). Al preguntar a otras 20 personas más, se ha obtenido otro array de 20 elementos.

In [10]:
import numpy as np

sangre1 = np.array(['O+', 'A-', 'B+', 'AB+', 'O-', 'A+', 'B-', 'O+', 'AB-', 'A+', 'B+', 'O-', 'A-', 'O+', 'AB+', 'B-', 'A+', 'O+', 'A-', 'B+'])
sangre2 = np.array(['A+', 'O+', 'O-', 'AB+', 'A-', 'B+', 'AB-', 'O+', 'B-', 'O+', 'A-', 'AB+', 'B+', 'A+', 'O-', 'B-', 'A+', 'AB-', 'O+', 'O-'])

2. Elabora, a partir de los dos arrays anteriores, un conjunto formado por los grupos sanguíneos que han aparecido en ambas encuestas. Finalmente, muestra el conjunto por pantalla.

In [14]:
grupos = np.intersect1d(sangre1, sangre2)

print(grupos)

['A+' 'A-' 'AB+' 'AB-' 'B+' 'B-' 'O+' 'O-']


## Ejercicio 48
1. Crea un array que contenga las aficiones/hobbies de 20 personas (fruto de otra encuesta). Al preguntar a otras 20 personas más, se ha obtenido otro array de 20 elementos.

In [15]:
import numpy as np

aficiones1 = np.array(['leer', 'viajar', 'deporte', 'cine', 'música', 'arte', 'teatro', 'naturaleza', 'fotografía', 'videojuegos',
                                'pintura', 'senderismo', 'cocina', 'jardinería', 'escribir', 'música', 'bailar', 'escuchar música', 'ciclismo', 'pesca'])

aficiones2 = np.array(['cocina', 'deporte', 'música', 'viajar', 'arte', 'senderismo', 'cine', 'videojuegos', 'bailar', 'teatro',
                                'lectura', 'ciclismo', 'escuchar música', 'fotografía', 'escribir', 'pintura', 'pesca', 'jardinería', 'bailar', 'naturaleza'])

2. Elabora, a partir de los dos arrays anteriores, un conjunto formado por las aficiones de la primera encuesta que no están presentes en las respuestas de las 20 últimas personas

In [16]:
aficiones_unicas = np.setdiff1d(aficiones1, aficiones2)

print(aficiones_unicas)

['leer']


## Ejercicio 49
1. Crea un array que contenga el lugar de nacimiento de 20 personas (fruto de una última encuesta). Al preguntar a otras 20 personas más, se ha obtenido otro array de 20 elementos.

In [17]:
import numpy as np

sitios1 = np.array(['Madrid', 'Barcelona', 'Sevilla', 'Valencia', 'Bilbao', 'Malaga', 'Zaragoza', 'Alicante', 'Granada', 'Oviedo',
                              'Santander', 'Córdoba', 'Badajoz', 'Murcia', 'La Coruña', 'Salamanca', 'Valladolid', 'Pamplona', 'Logroño', 'Huesca'])

sitios2 = np.array(['Madrid', 'Valencia', 'Alicante', 'Sevilla', 'Zaragoza', 'Granada', 'Murcia', 'Oviedo', 'Córdoba', 'Badajoz',
                              'Bilbao', 'Huesca', 'Salamanca', 'La Coruña', 'Santiago', 'Gijón', 'Pamplona', 'Logroño', 'Valladolid', 'San Sebastián'])

2. Elabora, a partir de los dos arrays anteriores, un conjunto formado por las localidades de la primera encuesta que no están presentes en la segunda y las de la segunda que no están presentes en la primera

In [18]:

diferentes = np.setxor1d(sitios1, sitios2)
diferentes2 = np.setxor1d(sitios2, sitios1)

print(diferentes)
print(diferentes2)

['Barcelona' 'Gijón' 'Malaga' 'San Sebastián' 'Santander' 'Santiago']
['Barcelona' 'Gijón' 'Malaga' 'San Sebastián' 'Santander' 'Santiago']


## Ejercicio 50
Calcula la hipotenusa de un triángulo rectángulo cuyo cateto base es igual a 7 y su cateto perpendicular es igual a 5. Finalmente, muestra el resultado por pantalla.

In [19]:
import numpy as np

base = 7
perpendicular = 5

hipotenusa = np.sqrt(base ** 2 + perpendicular ** 2)

print(hipotenusa)

8.602325267042627
